### ISSUE TITLE
Did you know about `hyperpolyglot`?

### ISSUE THREAD

**Issue by xiongtx** [chanshunli/fp-book#1]
Neat work; I hope you knew about [this](http://hyperpolyglot.org/lisp) though, so you don't have to write everything from scratch!

**Comment by xlisp** [comment]
Thanks @xiongtx , yes, i know it. I have updated the readme's declaration what the content forked form the http://hyperpolyglot.org/lisp, only for compare study lisp and record learning experience.
:+1:
